#pragma once

#include "CoreMinimal.h"
#include "JMJ_ProcessManager.h"
#include "JMJ_Demo_Backrooms.generated.h"


/*
  This infinite level generator splits the world into square 2D cells and runs MarkovJunior within each one.
  Each cell's MJ run is seeded with only its index + level seed, so they are deterministic and order-independent.
  To ensure neighboring cells connect nicely, the border pixels are pre-generated and fed to MJ,
    using randomness seeded by the edge ID + level seed.

  Each connecting pixel out from a new cell is given a "seal" actor, which triggers further level generation when "unsealed".
  Seals can take any form you want, for example:
    * An interactive door which is unsealed when opened for the first time.
    * An invisible trigger volume which is unsealed when players walk through it.

  Replication is respected, so that this level generator can be networked!
  However we don't take the extra effort to support late-joining players --
    we'd have to manually send the transform data for all existing static-mesh instances.
*/


/*
  To build your own game from this system, follow these steps:
    1. Build a child of ABackroomsSeal, to trigger further level generation at certain points (e.g. when players walk through it).
    2. Build a child of ABackroomsCell, to set up floor/ceiling/wall meshes. 
    3. Inherit from or configure UBackrooms_GM_Component, within a Game Mode, to use your own prefabs and parameters.
    4. Generation will immediately start on that Game-Mode component's BeginPlay.
    5. After BeginPlay you can call "GetRandomEmptyPos({ 0, 0 })" to find some initial spawn locations.
    6. If you wish, destroy the generated level early by destroying the GM component.
*/


class ABackroomsSeal;
class ABackroomsCell;

UDELEGATE()
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnBackroomsUnsealing, ABackroomsSeal*, seal);
UDELEGATE()
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnBackroomsCellGenerated,
											   const FJmjIntVector2D&, cellIdx,
											   ABackroomsCell*, cell,
											   const TArray<ABackroomsSeal*>&, seals);


//Sets up the backrooms level generation logic.
//
// 1. Inherit from this and provide prefabs, other data.
// 2. Attach to a Game Mode and generation immediately starts on BeginPlay.
// 3. Call "GetRandomEmptyPos({ 0, 0 })" to find initial spawn locations and teleport your players there.
// 4. Make sure there is some way to unseal your ABackroomsSeal's.
// 5. Destroy the generated level's actors by destroying this component.
//
//Note that the very first generated cell of the first game you play will take a few seconds to finish;
//  after that they should run near-instantaneous.
UCLASS(BlueprintType, Blueprintable, meta=(BlueprintSpawnableComponent))
class UBackrooms_GM_Component : public UActorComponent
{
	GENERATED_BODY()
public:

	//A root point for level generation, representing the min corner of the origin cell.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup")
	USceneComponent* Origin = nullptr;
	//The horizontal length of a single voxel, in world units.
	//Make sure it's at least as large as your player pawns!
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Size")
	float PixelLength = 200;
	//The height of the generated level, in world units.
	//No ceiling is generated by this logic; we leave that to you.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Size")
	float PixelHeight = 300;
	//The number of pixels along each generated cell.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Params", meta=(ClampMin=4))
	int CellResolution = 32;
	//The min number of connections along each edge connecting two cells.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Params", meta=(ClampMin=1))
	int MinEdgeConnections = 2;
	//The max number of connections along each edge connecting two cells.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Params", meta=(ClampMin=1))
	int MaxEdgeConnections = 6;
	//Set to a value other than 0 for a deterministic game.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Params")
	int Seed = 0;
	//The actor that renders meshes of a single cell.
	//The mesh is expected to be sized like a pixel of the generated world, with the origin at its min-corner.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Prefabs")
	TSubclassOf<ABackroomsCell> CellPrefab;
	//The actor for a single ceiling light.
	//The mesh is expected to fit inside one pixel of the generator grid,
	//  with the origin at the center-bottom, facing longways along the Y axis.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Prefabs")
	TSubclassOf<AActor> CeilingLightPrefab;
	//The specific kind of seal to use between cells.
	//It must be sized like a pixel of the generated world, with the origin at its min-corner.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Prefabs")
	TSubclassOf<ABackroomsSeal> SealPrefab;

	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly, Transient, Category="State")
	FJmjParsedAlgo JmjAlgo;
	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly, Transient, Category="State|Actors")
	TArray<ABackroomsSeal*> Seals;
	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly, Transient, Category="State|Actors")
	TMap<FJmjIntVector2D, ABackroomsCell*> ActiveCells;
	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly, Transient, Category="State|Actors")
	TArray<AActor*> CeilingLights;

	//Triggers once for each new cell that's generated.
	UPROPERTY(BlueprintAssignable)
	FOnBackroomsCellGenerated OnNewCellGenerated;
	
	
	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type reason) override;


	//Gets the cell the given position lies within.
	UFUNCTION(BlueprintCallable, BlueprintPure)
	FJmjIntVector2D GetCell(const FVector& worldPos) const;
	//Gets a random empty position within the given cell.
	//Fails (returns false) if that cell hasn't been generated.
	UFUNCTION(BlueprintCallable, BlueprintPure)
	bool GetRandomEmptyPos(const FJmjIntVector2D& cell, FJmjIntVector2D& outLocalPixel, FVector& outWorldFloorPos) const;
	//Gets the floor position of the given pixel, either at its center or its min.
	UFUNCTION(BlueprintCallable, BlueprintPure)
	FVector PixelIdxToWorldFloorPos(const FJmjIntVector2D& pixel, bool atMinCorner) const;
	
	//Immediately loads the given cell if it hasn't been already.
	//Returns false if it already existed (true if it really was just generated).
	//
	//Normally this is called internally as seals are unsealed.
	UFUNCTION(BlueprintCallable)
	bool LoadCell(const FJmjIntVector2D& cellIdx);

private:

	UFUNCTION(BlueprintCallable)
	void OnSealBroken(ABackroomsSeal* seal);

	TSet<int> bufferIntegerSet;
	TMap<FJmjIntVector2D, FJmjIntVector2D> bufferIdx2DMap;
	TArray<ABackroomsSeal*> bufferNewSeals;
};

//A physical block between two cells of the Backrooms level generator.
//When someone "unseals" it (e.g. it's a door and a player opens it),
//  it raises an event which triggers more level generation.
UCLASS(BlueprintType, Blueprintable)
class ABackroomsSeal : public AActor
{
	GENERATED_BODY()
public:

	//The index of the neighboring cell that will become unsealed.
	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly, Transient, Replicated)
	FJmjIntVector2D TargetCell;
	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly, Transient)
	bool IsStillSealed = true;

	//Raised on all machines (server and clients) when the unsealing happens.
	//Never triggers more than once.
	UPROPERTY(BlueprintAssignable)
	FOnBackroomsUnsealing OnUnsealed;

	//If this actor hasn't been unsealed yet, and we are authoritative (i.e. on the server),
	//  raises "OnUnsealed" and returns true.
	//Otherwise does nothing and returns false.
	UFUNCTION(BlueprintCallable)
	bool TriggerUnsealing_AuthorityOnly();

	
	ABackroomsSeal();
	void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;

private:

	UFUNCTION(NetMulticast, Reliable)
	void TriggerUnsealingRPC();
};

//A single square area that is filled in using a MarkovJunior algorithm.
UCLASS(BlueprintType)
class ABackroomsCell : public AActor
{
	GENERATED_BODY()
public:

	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly, Transient)
	class UJmjGrid2D* GeneratedGrid = nullptr;
	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly, Transient)
	FJmjIntVector2D Idx;
	UPROPERTY(BlueprintReadOnly, Transient)
	TArray<FVector3f> ServerInstanceLocations;

	//The mesh is expected to be sized to cover the entire cell, with its top at Z=0.
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Replicated)
	UStaticMeshComponent* FloorMesh;
	//The mesh is expected to be sized to cover the entire cell, with its bottom at the top of the cell space.
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Replicated)
	UStaticMeshComponent* CeilingMesh;
	//The mesh is expected to be sized like a pixel of the generated world, with the origin at its min-corner.
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Replicated)
	UInstancedStaticMeshComponent* WallMeshes;

	ABackroomsCell();
	void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;

	void FinalizeWallMeshInstances();

protected:

	UFUNCTION(NetMulticast, Reliable)
	void ReceiveMeshInstances(const TArray<FVector3f>& locations);
	
	void ActuallyApplyMeshInstances(const TArray<FVector3f>& locations);

private:

	TArray<FVector3f> rpcBuffer;
	TArray<FTransform> transformBuffer;
};