#pragma once

#include "CoreMinimal.h"
#include "JMJ_ProcessManager.h"
#include "JMJ_Demo_Backrooms.generated.h"


/*
  This infinite level generator splits the world into square 2D cells,
    pre-selects 1-N connecting pixels between each cell based on the level seed,
    then uses MarkovJunior to fill in each cell based on that boundary info.

  Each connecting pixel between two cells is given a "seal".
  When a seal is "unsealed", it triggers more level generation nearby to keep the infinite world going.
  Seals can take any form you want, for example:
    * An interactive door which is unsealed when opened for the first time
    * An invisible wall which is unsealed (and destroyed) when entering a player's line-of-sight.

  Replication is respected, so that this level generator can be networked!
  However we don't support late-joining players, as they would need to be manually sent
    any static-mesh instances which have been already loaded.
  Totally doable but I'm not bothering for a demo.
*/

class ABackroomsSeal;
class ABackroomsCell;

UDELEGATE()
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnBackroomsUnsealing, ABackroomsSeal*, seal);


//Sets up the backrooms level generation logic.
//
// 1. Inherit from this and provide prefabs, other data.
// 2. Create within a Game Mode to immediately start the generator.
// 3. Call "GetRandomEmptyPos({ 0, 0, 0 })" to find initial spawn locations and teleport your player there.
// 4. Make sure there is some way to unseal your ABackroomsSeal's.
// 5. Destroy the generated level's actors by destroying this component.
//
//Note that the very first generated cell of the first game you play will take a few seconds to finish;
//  after that they should run near-instantaneous.
UCLASS(BlueprintType, Blueprintable)
class UBackrooms_GM_Component : public UActorComponent
{
	GENERATED_BODY()
public:

	//A root point for level generation, representing the min corner of the origin cell.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup")
	USceneComponent* Origin = nullptr;
	//The horizontal length of a single voxel, in world units.
	//Make sure it's at least as large as your player pawns!
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Size")
	float PixelLength = 200;
	//The height of the generated level, in world units.
	//No ceiling is generated by this logic; we leave that to you.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Size")
	float PixelHeight = 300;
	//The number of pixels along each generated cell.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Params")
	int CellResolution = 32;
	//The min number of connections along each edge connecting two cells.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Params", meta=(ClampMin=1))
	int MinEdgeConnections = 2;
	//The max number of connections along each edge connecting two cells.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Params", meta=(ClampMin=1))
	int MaxEdgeConnections = 6;
	//Set to a value other than 0 for a deterministic game.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Params")
	int64 InitialSeed = 0;
	//The actor that renders meshes of a single cell.
	//The mesh is expected to be sized like a pixel of the generated world, with the origin at its min-corner.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Prefabs")
	TSubclassOf<ABackroomsCell> CellPrefab;
	//The specific kind of seal to use between cells.
	//It must be sized like a pixel of the generated world, with the origin at its min-corner.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Prefabs")
	TSubclassOf<ABackroomsSeal> SealPrefab;
	//A floor that spans a whole cell in size, and whose origin is on the min-top corner.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Prefabs")
	TSubclassOf<AActor> FloorPrefab;
	//A ceiling that spans a whole cell in size, and whose origin is on the min corner.
	UPROPERTY(BlueprintReadWrite, EditDefaultsOnly, Category="Setup|Prefabs")
	TSubclassOf<AActor> CeilingPrefab;

	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly, Category="State")
	TArray<ABackroomsSeal*> Seals;
	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly, Category="State")
	TArray<AActor*> Floors;
	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly, Category="State")
	TArray<AActor*> Ceilings;
	//(Z component is unused and always set to 0)
	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly, Category="State")
	TMap<FJmjIntVector2D, ABackroomsCell*> ActiveCells;
	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly, Category="State")
	FJmjParsedAlgo JmjAlgo;

	
	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type reason) override;


	//Gets the cell the given position lies within.
	UFUNCTION(BlueprintCallable, BlueprintPure)
	FJmjIntVector2D GetCell(const FVector& worldPos) const;
	//Gets a random empty position within the given cell.
	//Fails (returns false) if that cell hasn't been generated.
	UFUNCTION(BlueprintCallable, BlueprintPure)
	bool GetRandomEmptyPos(const FJmjIntVector2D& cell, FJmjIntVector2D& outLocalPixel, FVector& outWorldFloorPos) const;
	
	//Immediately loads the given cell if it hasn't been already.
	//Returns false if it already existed (true if it really was just generated).
	//
	//Normally this is called internally as seals are unsealed.
	UFUNCTION(BlueprintCallable)
	bool LoadCell(const FJmjIntVector2D& idx);

private:

	UFUNCTION(BlueprintCallable)
	void OnSealBroken(ABackroomsSeal* seal);
};

//A physical block between two cells of the Backrooms level generator.
//When someone "unseals" it (e.g. it's a door and a player opens it),
//  it raises an event which triggers more level generation.
UCLASS(BlueprintType, Blueprintable)
class ABackroomsSeal : public AActor
{
	GENERATED_BODY()
public:

	//The index of the neighboring cell that will become unsealed.
	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly)
	FJmjIntVector2D TargetCell;
	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly)
	bool IsStillSealed = true;

	//Raised on all machines (server and clients) when the unsealing happens.
	//Never triggers more than once.
	UPROPERTY(BlueprintAssignable)
	FOnBackroomsUnsealing OnUnsealed;

	//If this actor hasn't been unsealed yet, and we are authoritative (i.e. on the server),
	//  raises "OnUnsealed" and returns true.
	//Otherwise does nothing and returns false.
	UFUNCTION(BlueprintCallable)
	bool TriggerUnsealing_AuthorityOnly();

	
	ABackroomsSeal();
	void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;
	
	virtual void BeginPlay() override;

private:

	UFUNCTION(NetMulticast, Reliable)
	void TriggerUnsealingRPC();
	void TriggerUnsealingLocalLogic();
};

//A single square area that is filled in using a MarkovJunior algorithm.
UCLASS(BlueprintType)
class ABackroomsCell : public AActor
{
	GENERATED_BODY()
public:

	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly)
	class UJmjGrid2D* GeneratedGrid = nullptr;
	UPROPERTY(BlueprintReadOnly, VisibleInstanceOnly)
	FJmjIntVector2D Idx;

	//The mesh is expected to be sized like a pixel of the generated world, with the origin at its min-corner.
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere, Replicated)
	UInstancedStaticMeshComponent* WallMeshes;

	ABackroomsCell();
	void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;
};