#pragma once

#include "CoreMinimal.h"

#include "JMJ_Constants.h"
#include "JMJ_ProcessManager.h"

#include "JMJ_Grids.generated.h"


//Convenience class for a 2D grid of pixels generated by JMarkovJunior.
UCLASS(BlueprintType, DisplayName="JMJ Grid 2D")
class JMARKOVJUNIOR_API UJmjGrid2D : public UObject
{
	GENERATED_BODY()
public:

	UFUNCTION(BlueprintCallable, DisplayName="JMJ Grid 2D from current algo state")
	static UJmjGrid2D* CreateFromAlgorithmState(const struct FJmjAlgoState& state,
												UObject* owner = nullptr,
												FName objName = NAME_None,
												bool isTransient = true);
	

	const auto& GetBytes() const { return Bytes; }
	const auto& GetResolution() const { return Resolution; }

	auto ByteAt(const FJmjIntVector2D& pixel) const { return Bytes[pixel.X + (pixel.Y * Resolution.X)]; }
	auto& ByteAt(const FJmjIntVector2D& pixel) { return Bytes[pixel.X + (pixel.Y * Resolution.X)]; }

	//Checks whether the given pixel index is within this grid.
	UFUNCTION(BlueprintCallable, BlueprintPure)
	bool IsIndexInGrid(const FJmjIntVector2D& pixel) const;
	
	//Gets the value of this grid at the given pixel.
	//
	//You can choose what value is returned when going outside the array;
	//    by default it's 255 which will log an error on being returned.
	UFUNCTION(BlueprintCallable, BlueprintPure)
	uint8 GetValue(const FJmjIntVector2D& pixel, uint8 valueOutsideArray = 255) const;
	//Checks whether the given pixel is the given color, by its single char or full name.
	//If you want pixels outside the grid to silently return false, pass 'true' for the third argument.
	UFUNCTION(BlueprintCallable, BlueprintPure)
	bool IsPixelColor(const FJmjIntVector2D& pixel, const FString& colorID, bool allowOutside = false) const;
	
	UFUNCTION(BlueprintCallable, BlueprintPure)
	int CountPixelsOfColor(const FString& colorID) const;

	//Updates this grid object to hold the current state of the given running algorithm.
	UFUNCTION(BlueprintCallable)
	void DownloadFromAlgorithm(const struct FJmjAlgoState& state);
	//Sets up this object with a new grid, whose contents are uninitialized.
	//Ideally you will fill the values in using 'ForEach'.
	void InitializeWithResolution(const FJmjIntVector2D& resolution)
	{
		Resolution = resolution;
		Bytes.SetNumUninitialized(Resolution.X * Resolution.Y, EAllowShrinking::No);
	}

	
	//Iterates over every value in this grid and invokes your lambda on it,
	//   passing the index and a reference to the grid element.
	//
	//To interrupt the loop, have your lambda return true
	//  (then this function returns whether the interrupt occurred).
	template<typename Func>
	auto ForEach(Func&& toDo)
	{
		constexpr bool ReturnsBool = std::is_same_v<bool, std::invoke_result_t<Func, FJmjIntVector2D, uint8&>>;

		int i = 0;
		for (int x = 0; x < Resolution.X; x++)
			for (int y = 0; y < Resolution.Y; y++)
			{
				FJmjIntVector2D pixel{ x, y };
				if constexpr (ReturnsBool)
				{
					if (std::invoke(toDo, pixel, Bytes[i]))
						return true;
				}
				else
				{
					std::invoke(toDo, pixel, Bytes[i]);
				}

				i += 1;
			}

		if constexpr (ReturnsBool)
			return false;
	}
	//Iterates over every value in this grid and invokes your lambda on it,
	//   passing the index and the grid element.
	//
	//To interrupt the loop, have your lambda return true
	//  (then this function returns whether the interrupt occurred).
	template<typename Func>
	auto ForEach(Func&& toDo) const
	{
		constexpr bool ReturnsBool = std::is_same_v<bool, std::invoke_result_t<Func, FJmjIntVector2D, uint8>>;

		int i = 0;
		for (int x = 0; x < Resolution.X; x++)
			for (int y = 0; y < Resolution.Y; y++)
			{
				FJmjIntVector2D pixel{ x, y };
				if constexpr (ReturnsBool)
				{
					if (std::invoke(toDo, pixel, Bytes[i]))
						return true;
				}
				else
				{
					std::invoke(toDo, pixel, Bytes[i]);
				}

				i += 1;
			}

		if constexpr (ReturnsBool)
			return false;
	}
	

protected:

	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TArray<uint8> Bytes;
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FJmjIntVector2D Resolution;

private:

	TArray<int> resolutionBuffer;
};


//Convenience class for a 3D grid of pixels generated by JMarkovJunior.
UCLASS(BlueprintType, DisplayName="JMJ Grid 3D")
class JMARKOVJUNIOR_API UJmjGrid3D : public UObject
{
	GENERATED_BODY()
public:

	UFUNCTION(BlueprintCallable, DisplayName="JMJ Grid 3D from current algo state")
	static UJmjGrid3D* CreateFromAlgorithmState(const struct FJmjAlgoState& state,
												UObject* owner = nullptr,
												FName objName = NAME_None,
												bool isTransient = true);
	

	const auto& GetBytes() const { return Bytes; }
	const auto& GetResolution() const { return Resolution; }

	auto ByteAt(const FIntVector& pixel) const { return Bytes[pixel.X + (Resolution.X * (pixel.Y + (Resolution.Y * pixel.Z)))]; }
	auto& ByteAt(const FIntVector& pixel) { return Bytes[pixel.X + (Resolution.X * (pixel.Y + (Resolution.Y * pixel.Z)))]; }

	//Checks whether the given pixel index is within this grid.
	UFUNCTION(BlueprintCallable, BlueprintPure)
	bool IsIndexInGrid(const FIntVector& pixel) const;
	
	//Gets the value of this grid at the given pixel.
	//
	//You can choose what value is returned when going outside the array;
	//    by default it's 255 which will log an error on being returned.
	UFUNCTION(BlueprintCallable, BlueprintPure)
	uint8 GetValue(const FIntVector& pixel, uint8 valueOutsideArray = 255) const;
	//Checks whether the given pixel is the given color, by its single char or full name.
	//If you want pixels outside the grid to silently return false, pass 'true' for the third argument.
	UFUNCTION(BlueprintCallable, BlueprintPure)
	bool IsPixelColor(const FIntVector& pixel, const FString& colorID, bool allowOutside = false) const;
	
	UFUNCTION(BlueprintCallable, BlueprintPure)
	int CountPixelsOfColor(const FString& colorID) const;

	//Updates this grid object to hold the current state of the given running algorithm.
	UFUNCTION(BlueprintCallable)
	void DownloadFromAlgorithm(const struct FJmjAlgoState& state);
	//Sets up this object with a new grid, whose contents are uninitialized.
	//Ideally you will fill the values in using 'ForEach'.
	void InitializeWithResolution(const FIntVector& resolution)
	{
		Resolution = resolution;
		Bytes.SetNumUninitialized(Resolution.X * Resolution.Y * Resolution.Z, EAllowShrinking::No);
	}

	
	//Iterates over every value in this grid and invokes your lambda on it,
	//   passing the index and a reference to the grid element.
	//
	//To interrupt the loop, have your lambda return true
	//  (then this function returns whether the interrupt occurred).
	template<typename Func>
	auto ForEach(Func&& toDo)
	{
		constexpr bool ReturnsBool = std::is_same_v<bool, std::invoke_result_t<Func, FIntVector, uint8&>>;

		int i = 0;
		for (int x = 0; x < Resolution.X; x++)
			for (int y = 0; y < Resolution.Y; y++)
				for (int z = 0; z < Resolution.Z; ++z)
				{
					FIntVector pixel{ x, y, z };
					if constexpr (ReturnsBool)
					{
						if (std::invoke(toDo, pixel, Bytes[i]))
							return true;
					}
					else
					{
						std::invoke(toDo, pixel, Bytes[i]);
					}

					i += 1;
				}

		if constexpr (ReturnsBool)
			return false;
	}
	//Iterates over every value in this grid and invokes your lambda on it,
	//   passing the index and the grid element.
	//
	//To interrupt the loop, have your lambda return true
	//  (then this function returns whether the interrupt occurred).
	template<typename Func>
	auto ForEach(Func&& toDo) const
	{
		constexpr bool ReturnsBool = std::is_same_v<bool, std::invoke_result_t<Func, FIntVector, uint8>>;

		int i = 0;
		for (int x = 0; x < Resolution.X; x++)
			for (int y = 0; y < Resolution.Y; y++)
				for (int z = 0; z < Resolution.Z; ++z)
				{
					FIntVector pixel{ x, y, z };
					if constexpr (ReturnsBool)
					{
						if (std::invoke(toDo, pixel, Bytes[i]))
							return true;
					}
					else
					{
						std::invoke(toDo, pixel, Bytes[i]);
					}

					i += 1;
				}

		if constexpr (ReturnsBool)
			return false;
	}
	

protected:

	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	TArray<uint8> Bytes;
	UPROPERTY(BlueprintReadOnly, VisibleAnywhere)
	FIntVector Resolution;

private:

	TArray<int> resolutionBuffer;
};